name: GitHub Actions - Pull - Branch Template
run-name: Running - ${{ github.event_name }}
on:
  pull_request:
    branches:
      # - develop
      - master
jobs:
  on-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "Comentário PULL REQUEST WORKFLOW - branch"