name: GitHub Actions - Worflow dispatch Template - String
run-name: Running - ${{ github.event_name }}
on:
  workflow_dispatch:
    inputs:
      browser:
        description: Selecione Browser
        type: string
jobs:
  on-workflow_dispatch:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "Comentário Worflow dispatch - Browser: ${{inputs.browser}}"