name: GitHub Actions - Worflow dispatch
run-name: Running - ${{ github.event_name }}
on:
  workflow_dispatch:
    inputs:
      tags:
        description: Selecione a tag
        type: choice
        options:
        - tag_1
        - tag_2
        - tag_3
        default: 'tag_1'
        required: true
      browser:
        description: Selecione o Browser
        type: string
      severidade:
        description: funcionalidade crítica?
        type: boolean

jobs:
  on-workflow_dispatch:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "Tag: ${{inputs.tags}}"
          echo "browser: ${{inputs.browser}}"
          echo "severidade: ${{inputs.severidade}}"
