name: GitHub Actions - Workflow run branches
run-name: Running - Workflow run branches
on: 
  workflow_run:
    workflows: [GitHub Actions - Trigger 1]
    branches: [master]
jobs:
  on-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "Workflow que foi trigado"
