name: GitHub Actions - Trigger 2
run-name: Running - Trigger 2
on: [push, workflow_dispatch]
jobs:
  on-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "Trigger finalizado"