name: GitHub Actions - Push Template Básico
run-name: Running - ${{ github.event_name }}
on: [push]
jobs:
  on-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: |
          echo "Comentário PUSH WORKFLOW - Basic"