name: GitHub Actions - Configuração de Secret de Repositório
run-name: Running - Secret Repo Config
on: [push, workflow_dispatch]
jobs:
  on-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Comentário
        run: |
          echo "${{secrets.test_secret}}"